name: 🧪 Cypress Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      # 🧠 Optional: Start your local app (if you need a frontend running)
      # - name: Start Noveli app
      #   run: npm run dev &
      #   env:
      #     NODE_ENV: test
      #   shell: bash

      - name: Run Protected features tests
        run: npx cypress run --spec "cypress/e2e/protected-features.cy.js"
        env:
          CYPRESS_username: ${{ secrets.CYPRESS_username }}
          CYPRESS_password: ${{ secrets.CYPRESS_password }}
